Dont call
Roave/Dont pull request #10
Opened 2019-02-08 10:50 UTC by BackEndTea

Following [this](https://twitter.com/BackEndTea/status/1093809127246258177) twitter conversation.

I'm partial to making the error text a refference to Carly Rae Jespens 'Call me maybe', but i couldn't think of anything.

2019-02-08 10:51 UTC, asgrim requested changes

2019-02-08 10:51 UTC, asgrim commented on src/Dont/DontCall.php
> +    final public function __call($name, $arguments)
No `__callStatic`?

2019-02-08 10:51 UTC, asgrim commented on src/Dont/DontCall.php
> +trait DontCall
`README.md` needs updating to add this please

2019-02-08 11:17 UTC, BackEndTea commented on src/Dont/DontCall.php
> +    final public function __call($name, $arguments)
Added a callStatic one as well

2019-03-16 18:58 UTC, Ocramius approved these changes
Damn, this was just sitting around! :+1:

2019-03-16 18:59 UTC, merged

2019-03-16 21:31 UTC, BackEndTea commented
Thank you @Ocramius & @asgrim