Upgrade (De)Serialization checks for PHP 7.4
Roave/Dont pull request #22
Opened 2020-01-05 16:07 UTC by lexidor

Fixes #21

2020-01-05 16:20 UTC, lexidor commented
Hi Ocramius. Should we continue the conversation in the issue or start anew here in the PR? I have a question about the red :x: from travis. English is not m first language. What does it mean and what can I do to turn it into a green :heavy_check_mark:?

2020-01-05 17:12 UTC, lexidor commented
I don't know what formatter you use.
If this does not match your expectations, feel free to make a formatting commit.

2020-01-05 17:16 UTC, lexidor commented
I would recommend a squashed merge, because there are many intermediary commits.

2020-01-06 12:18 UTC, Ocramius requested changes
Looks good: don't worry about the repeated commits though, the merge commit is more relevant to me.

2020-01-06 12:18 UTC, Ocramius commented on tests/DontTest/DontDeserialiseTest.php
> +        } catch (NonDeserialisableObject $_) {
This should be multiple test methods, using `$this->expectException(NonDeserialisableObject::class)` each

2020-01-06 12:18 UTC, Ocramius commented on tests/DontTest/DontSerialiseTest.php
> +            self::markAsFailed('This method must always throw');
Similar to the above: need `$this->expectException()` and separate tests instead

2020-01-06 12:18 UTC, Ocramius commented on tests/DontTest/DontDeserialiseTest.php
> +        if($className === 'DontTestAsset\\NonDeserialisableImplementingSerializable'){
`NonDeserialisableImplementingSerializable::class` should be used here

2020-01-07 21:04 UTC, Ocramius approved these changes
Thanks @lexidor!

2020-01-07 21:04 UTC, merged